# Generated by Django 4.2.5 on 2023-11-07 16:06

import app_album_viewer.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cover', models.ImageField(default='coverImage.png', upload_to='uploads')),
                ('title', models.CharField(default=None, max_length=50)),
                ('desciption', models.CharField(max_length=100)),
                ('artist', models.CharField(default=None, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_of_format', models.CharField(choices=[('D', 'Digital Download'), ('C', 'CD'), ('V', 'Vinyl')], default='D', max_length=1)),
                ('release_date', models.DateTimeField(default=datetime.date(2023, 11, 7), validators=[app_album_viewer.models.validate_release_date])),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=50)),
                ('user_display_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=50)),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('albums', models.ManyToManyField(to='app_album_viewer.album')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Anonymous', max_length=50)),
                ('comment', models.CharField(max_length=200)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.song')),
            ],
        ),
    ]
