# Generated by Django 4.2.5 on 2023-11-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcomments',
            name='song',
        ),
    ]
