# Generated by Django 4.2.5 on 2023-11-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0002_remove_albumcomments_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcomments',
            name='album',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.album'),
            preserve_default=False,
        ),
    ]
