# Generated by Django 4.2.5 on 2023-11-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_album_viewer', '0004_alter_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default=None, max_length=50)),
                ('owned', models.ManyToManyField(to='app_album_viewer.album')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReccomendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.ManyToManyField(to='app_album_viewer.album')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.appusers')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
