# Generated by Django 4.2.5 on 2023-11-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0005_appusers_userreccomendations_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.album')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.appusers')),
            ],
        ),
        migrations.DeleteModel(
            name='UserReccomendations',
        ),
    ]
