# Generated by Django 4.2.5 on 2023-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0006_userrecommendations_delete_userreccomendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='coverImage', upload_to='uploads'),
        ),
    ]
