# Generated by Django 4.2.5 on 2023-11-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0007_alter_album_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='owned',
            new_name='album',
        ),
    ]
