# Generated by Django 4.2.5 on 2023-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0008_rename_owned_appusers_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusers',
            name='album',
        ),
    ]
