# Generated by Django 4.2.5 on 2023-11-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0010_alter_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecommendations',
            old_name='recommendations',
            new_name='album',
        ),
    ]
