# Generated by Django 4.2.5 on 2023-11-18 13:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0012_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
